# Generated by Django 2.1.1 on 2020-09-06 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_token', models.CharField(max_length=50)),
                ('date_request', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
