# Generated by Django 2.1.1 on 2020-09-06 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('realtor_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254)),
                ('realtor_of_month', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
